export const products = [
  {
    id: 1,
    image: '/images/Component_11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '65%',
    stock: 100,
    category: 'Office & Stationery',
    brand: 'KNI',
    minPurchase: 1,
    unitWeight: '500g',
    sizeDimensions: '30x20x5cm',
    seller: 'PT KNI',
    bumn: 'Telkom',
    totalSales: 500,
    description: 'Buku kas ukuran kwart. Cocok untuk kantor atau usaha kecil dalam mencatat transaksi.',
  },
  {
    id: 2,
    image: '/images/Component_12.png',
    title: 'BUKU KAS BESAR KNI | BUKU KEUANGAN',
    price: '15.000',
    location: 'Surabaya',
    rating: 4.7,
    sold: 180,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '50%',
    stock: 80,
    category: 'Office & Stationery, Lainnya, Alat Tulis',
    brand: 'KNI',
    minPurchase: 1,
    unitWeight: '700g',
    sizeDimensions: '35x25x7cm',
    seller: 'PT KNI Surabaya',
    bumn: 'Telkom',
    totalSales: 400,
    description: 'Buku kas besar cocok untuk pencatatan usaha besar dan menengah.',
  },
  {
    id: 3,
    image: '/images/Component_13.png',
    title: 'BUKU KAS KECIL KNI | BUKU KEUANGAN',
    price: '8.500',
    location: 'Bandung',
    rating: 4.9,
    sold: 300,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '80%',
    stock: 150,
    category: 'Office & Stationery, Lainnya, Alat Tulis',
    brand: 'KNI',
    minPurchase: 1,
    unitWeight: '400g',
    sizeDimensions: '25x15x4cm',
    seller: 'PT KNI Bandung',
    bumn: 'Telkom',
    totalSales: 600,
    description: 'Buku kas kecil cocok untuk keperluan pencatatan harian.',
  }
];
