export const products = [
  {
    id: 1,
    image: '/images/Component 11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    brand: 'KNI',
    category: 'ATK',
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '-',
    bumn: 'Telkom',
  },
  {
    id: 2,
    image: '/images/Component 11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    brand: 'KNI',
    category: 'ATK',
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '-',
    bumn: 'Telkom',
  },
  {
    id: 3,
    image: '/images/Component 11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    brand: 'KNI',
    category: 'ATK',
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '-',
    bumn: 'Telkom',
  },
  {
    id: 4,
    image: '/images/Component 11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    brand: 'KNI',
    category: 'ATK',
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '-',
    bumn: 'Telkom',
  },
  {
    id: 5,
    image: '/images/Component 11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    brand: 'KNI',
    category: 'ATK',
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '-',
    bumn: 'Telkom',
  },
  {
    id: 6,
    image: '/images/Component 11.png',
    title: 'BUKU KAS KNI UKURAN KWARTO | BUKU KEUANGAN',
    price: '10.545',
    location: 'Jakarta Timur',
    rating: 4.8,
    brand: 'KNI',
    category: 'ATK',
    sold: 235,
    taxes: 'PPN, PPh22, PKP',
    tkdn: '-',
    bumn: 'Telkom',
  },
  // Add more products as needed
];
